services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.45
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:9080
      - --entrypoints.websecure.address=:9443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --log.level=INFO
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik-monitoring.tp.local`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
    networks:
      - monitoring-network

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    extra_hosts:
      - "wordpress.tp.local:192.168.5.2"
      - "pma.tp.local:192.168.5.2"
      - "keycloak.tp.local:192.168.5.2"
      - "traefik-app.tp.local:192.168.5.2"
      - "kibana.tp.local:192.168.5.2"
      - "traefik-logging.tp.local:192.168.5.2"
      - "uptime.tp.local:192.168.5.2"
      - "traefik-monitoring.tp.local:192.168.5.2"
    volumes:
      - uptime-data:/app/data
      - /opt/tp-certs/ca.crt:/etc/ssl/certs/tp-ca.crt:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`uptime.tp.local`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
    networks:
      - monitoring-network

volumes:
  uptime-data:

networks:
  monitoring-network:
    driver: bridge
